server:
  port: 8888
spring:
  application:
    name: ms-twitter-sourcing
  profiles:
    active:
      master
  config:
    import: configserver:http://localhost:8888
  cloud:
    gcp:
      core:
        enabled: false
      logging:
        enabled: false