steps:
  - name: maven:3.8.4-eclipse-temurin-17
    entrypoint: mvn
    args: ["verify"]
  - name: maven:3.8.4-eclipse-temurin-17
    entrypoint: mvn
    args: ["test"]
  - name: maven:3.8.4-eclipse-temurin-17
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: [
        "build", "-t", "$_GCP_REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$_GCP_REGISTRY_REPO/api-clients:$COMMIT_SHA",
        "-t", "$_GCP_REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$_GCP_REGISTRY_REPO/api-clients:latest",
        "-f", "Dockerfile",
        "."
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
        "push",
        "$_GCP_REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$_GCP_REGISTRY_REPO/api-clients:$COMMIT_SHA",
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
        "push",
        "$_GCP_REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$_GCP_REGISTRY_REPO/api-clients:latest",
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-clients'
      - '--image'
      - '$_GCP_REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$_GCP_REGISTRY_REPO/api-clients:$COMMIT_SHA'
      - '--region'
      - '$_GCP_REGISTRY_REGION'
      - '--allow-unauthenticated'
images: [
    "$_GCP_REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$_GCP_REGISTRY_REPO/api-clients:$COMMIT_SHA",
    "$_GCP_REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$_GCP_REGISTRY_REPO/api-clients:latest"
]