steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["verify"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/api-clients:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/api-clients:latest" ]
images: ["gcr.io/$PROJECT_ID/api-clients:latest", "gcr.io/$PROJECT_ID/api-clients:$COMMIT_SHA"]