spring:
  datasource:
    url: jdbc:oracle:thin:@<HOST>:<PORT>:<SERVICE>
    username: <USER>
    password: <PASS>
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false

# For handling http errors
server:
  error:
    include-message: always
    include-stacktrace: never

# Used with spring actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - httptrace
